name: Deploy to AKS

on:
  push:
    branches:
      - main  # Trigger deployment on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group aks-dev-rg --name myAKSCluster --overwrite-existing

    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f k8s-specifications/db-deployment.yaml
        kubectl apply -f k8s-specifications/db-service.yaml
        kubectl apply -f k8s-specifications/redis-deployment.yaml
        kubectl apply -f k8s-specifications/redis-service.yaml
        kubectl apply -f k8s-specifications/vote-deployment.yaml
        kubectl apply -f k8s-specifications/vote-service.yaml
        kubectl apply -f k8s-specifications/result-deployment.yaml
        kubectl apply -f k8s-specifications/result-service.yaml
        kubectl apply -f k8s-specifications/worker-deployment.yaml

    - name: Verify deployments
      run: |
        kubectl get pods
        kubectl get svc